version: "3.9"

services:
  gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "8080:80"
    depends_on:
      - pedidos
    networks:
      - pedidos-net

  pedidos:
    image: hashicorp/http-echo
    container_name: servico-pedidos
    command: ["-text=Serviço de Pedidos ativo"]
    networks:
      - pedidos-net

  pagamentos:
    image: hashicorp/http-echo
    container_name: servico-pagamentos
    command: ["-text=Serviço de Pagamentos ativo"]
    networks:
      - pedidos-net

  estoque:
    image: hashicorp/http-echo
    container_name: servico-estoque
    command: ["-text=Serviço de Estoque ativo"]
    networks:
      - pedidos-net

  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: pedidos
      POSTGRES_USER: pedidos_user
      POSTGRES_PASSWORD: pedidos_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pedidos-net

networks:
  pedidos-net:
    driver: bridge

volumes:
  pgdata:
