apiVersion: apps/v1
kind: Deployment
metadata:
  name: estoque
spec:
  replicas: 1
  selector:
    matchLabels:
      app: estoque
  template:
    metadata:
      labels:
        app: estoque
    spec:
      containers:
        - name: estoque
          image: estoque:latest
          ports:
            - containerPort: 8080
